# Generated by Django 5.2.7 on 2025-11-03 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('version', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='expenses.category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'category_id', '-version'],
                'unique_together': {('project', 'category', 'version')},
            },
        ),
    ]
