# Generated by Django 5.2.7 on 2025-11-03 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investors.investor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['investor', 'project'], name='investment__investo_59006b_idx')],
            },
        ),
    ]
