# Generated by Django 5.2.7 on 2025-11-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('leilao', 'Leilão'), ('construcao', 'Construção'), ('reforma', 'Reforma')], max_length=20)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_obra', 'Em obra'), ('a_venda', 'À venda'), ('vendido', 'Vendido'), ('encerrado', 'Encerrado')], default='planejado', max_length=20)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_sale_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_sale_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
