# Generated by Django 5.2.7 on 2025-11-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_share_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shareholders',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
