# Generated by Django 5.2.7 on 2025-11-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_shareholders'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
